### PR TITLE
Simple stat check for ASDF clone dir

### LINKED ISSUE #1: Issue: If ASDF is already installed, the plugin fails
The git clone fails in `tasks/nstall.yml` if asdf is already installed for the user.  Fix this with a simple check, submitting a PR soon.

### PR DESCRIPTION
**Pull request by arevak**

### CODE REVIEW

**Comment by niall-byrne** [comment]
Thanks for the PR.  Please see the updated comments in the [issue](https://github.com/osx-provisioner/role-asdf/issues/1) you filed.  I just want to understand the problem clearly before we proceed.

**Comment by niall-byrne** [comment]
@arevak please take a look at the new molecule test and my variation on your solution.  I believe this solves this issue.

**Comment by arevak** [comment]
Apologies, I'll try to carve out some time soon, work has been really hectic.

**Comment by cschiewek** [comment]
@arevak Any chance we could get this reviewed and merged?  Let me know if there's anything I can do to help that along.

**Comment by niall-byrne** [comment]
I think I will simply merge this, I believe the issue is resolved.

**Pull request merged**
